// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// logistic_regression_beta
arma::vec logistic_regression_beta(arma::vec y, arma::mat X);
RcppExport SEXP _ridgeLR_logistic_regression_beta(SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_regression_beta(y, X));
    return rcpp_result_gen;
END_RCPP
}
// ridge_logistic_regression_beta2
arma::vec ridge_logistic_regression_beta2(arma::vec y, arma::mat X, double lambda);
RcppExport SEXP _ridgeLR_ridge_logistic_regression_beta2(SEXP ySEXP, SEXP XSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_logistic_regression_beta2(y, X, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ridgeLR_logistic_regression_beta", (DL_FUNC) &_ridgeLR_logistic_regression_beta, 2},
    {"_ridgeLR_ridge_logistic_regression_beta2", (DL_FUNC) &_ridgeLR_ridge_logistic_regression_beta2, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ridgeLR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
