# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logistic_regression_beta <- function(y, X) {
    .Call('_ridgeLR_logistic_regression_beta', PACKAGE = 'ridgeLR', y, X)
}

ridge_logistic_regression_beta2 <- function(y, X, lambda) {
    .Call('_ridgeLR_ridge_logistic_regression_beta2', PACKAGE = 'ridgeLR', y, X, lambda)
}

